export const VAULT_ITEM_REPOSITORY = Symbol('VAULT_ITEM_REPOSITORY');
export const VAULT_ACCESS_LOG_REPOSITORY = Symbol(
  'VAULT_ACCESS_LOG_REPOSITORY',
);
export const VAULT_SALT_REPOSITORY = Symbol('VAULT_SALT_REPOSITORY');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
